### ISSUE TITLE
Adding support for MonoLisa 2.003 Complete

### ISSUE THREAD

**Issue by Bad3r** [daylinmorgan/monolisa-nerdfont-patch#1]
Hi,
Thank you for making this! I love MonoLisa, and with nerdfonts it's even better.
I am curious if you plan to add support for the next major release, MonoLisa 2.0.

Currently, the latest version is: [v2.002 (Prerelease)](https://www.monolisa.dev/releases)

There are major changes in this update such as only providing TTF files (no OTF anymore) and they added a new feature `variable fonts` that is not supported yet by this patch.

**Comment by daylinmorgan** [comment]
I was waiting until they finalized the version to specify that it works. But in my testing there doesn't appear to be any notable differences when applying the nerd fonts.

I don't think the variable fonts feature will have any bearing on the icons themselves.

Have you tested patching `v2.002` and come across any issues?

**Comment by Bad3r** [comment]
@daylinmorgan Yeah it makes sense to wait for a release. 

> Have you tested patching `v2.002` and come across any issues?

Some minor things. For example only added the ttf folder and files then ran make. This resulted in an error because the script expects otf files to exist as well. 

As a minor improvement it would be nice to check which folders/files exist in the tree "./MonoLisa" and only apply the patch to them. 

The second issue is when I added the "./MonoLisa/variable" folder and files. The script crashed due to unexpected files/folder.

**Comment by daylinmorgan** [comment]
> Some minor things. For example I only added the ttf folder and files then ran make. This resulted in an error because the script expects otf files to exist as well.

You may have still had an `otf` directory in `./MonoLisa`.

> As a minor improvement it would be nice to check which folders/files exist in the tree "./MonoLisa" and only apply the patch to them.

This was the purpose of the `ML_TYPES` variable in the `Makefile` but it wasn't ignoring empty directories. I've modified it to ignore empty directories.

> The second issue is when I added the "./MonoLisa/variable" folder and files. The script crashed due to unexpected files/folder.

The scripts currently expect the `./MonoLisa` directory to have a fairly flat file structure with all fonts of a particular type in their own directory. Is there a particular need to have a `variable` directory? Maybe you receive a different product from me but from my personal license I just get the following: 

```
.
├── license.md
├── README.md
└── ttf
    ├── MonoLisa-BoldItalic.ttf
    ├── MonoLisa-Bold.ttf
    ├── MonoLisa-RegularItalic.ttf
    └── MonoLisa-Regular.ttf
```

**Comment by Bad3r** [comment]
> You may have still had an `otf` directory in `./MonoLisa`.

Yes, you are correct. I did have an empty folder there. Thanks for the fix.  
  
> Is there a particular need to have a `variable` directory? Maybe you receive a different product from me but from my personal license I just get the following

Yes. My folder structure is different. I thinks its due to me having the professional version of the font ([[MonoLisa](https://www.monolisa.dev/buy))
```
 .
├──  license.md
├──  README.md
├──  ttf
│  ├──  MonoLisa-Black.ttf
│  ├──  MonoLisa-BlackItalic.ttf
│  ├──  MonoLisa-Bold.ttf
│  ├──  MonoLisa-BoldItalic.ttf
│  ├──  MonoLisa-ExtraBold.ttf
│  ├──  MonoLisa-ExtraBoldItalic.ttf
│  ├──  MonoLisa-ExtraLight.ttf
│  ├──  MonoLisa-ExtraLightItalic.ttf
│  ├──  MonoLisa-Light.ttf
│  ├──  MonoLisa-LightItalic.ttf
│  ├──  MonoLisa-Medium.ttf
│  ├──  MonoLisa-MediumItalic.ttf
│  ├──  MonoLisa-Regular.ttf
│  ├──  MonoLisa-RegularItalic.ttf
│  ├──  MonoLisa-SemiBold.ttf
│  ├──  MonoLisa-SemiBoldItalic.ttf
│  ├──  MonoLisa-Thin.ttf
│  └──  MonoLisa-ThinItalic.ttf
└──  variable
   ├──  MonoLisaItalic.ttf
   └──  MonoLisaNormal.ttf
```

**Comment by daylinmorgan** [comment]
with `ee0e7911d8f0bac95da710982068a54acf4ca2a6` this directory structure should be no problem. Let me know if there are still issues.

**Comment by Bad3r** [comment]
Thank you! will test and report back. For record sake here is the V2.003 file strucute:
```
 MonoLisa-Complete-2.003
├──  faq.html
├──  ttf - static
│  ├──  MonoLisa-Black.ttf
│  ├──  MonoLisa-BlackItalic.ttf
│  ├──  MonoLisa-Bold.ttf
│  ├──  MonoLisa-BoldItalic.ttf
│  ├──  MonoLisa-ExtraBold.ttf
│  ├──  MonoLisa-ExtraBoldItalic.ttf
│  ├──  MonoLisa-ExtraLight.ttf
│  ├──  MonoLisa-ExtraLightItalic.ttf
│  ├──  MonoLisa-Light.ttf
│  ├──  MonoLisa-LightItalic.ttf
│  ├──  MonoLisa-Medium.ttf
│  ├──  MonoLisa-MediumItalic.ttf
│  ├──  MonoLisa-Regular.ttf
│  ├──  MonoLisa-RegularItalic.ttf
│  ├──  MonoLisa-SemiBold.ttf
│  ├──  MonoLisa-SemiBoldItalic.ttf
│  ├──  MonoLisa-Thin.ttf
│  ├──  MonoLisa-ThinItalic.ttf
│  ├──  MonoLisaItalic.ttf
│  └──  MonoLisaNormal.ttf
└──  ttf - variable
   ├──  README.md
   └──  ttf
      ├──  MonoLisaItalic.ttf
      └──  MonoLisaNormal.ttf
```      ``````

**Comment by Bad3r** [comment]
Hmm it failed because the folder names do not match. Also in the latest release the variable fonts are nested inside another folder.
```py
monolisa-nerdfont-patch  main 🐧 
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

monolisa-nerdfont-patch  main 🐧 
❯ tree MonoLisa 
MonoLisa
├── faq.html
├── ttf - static
│  ├── MonoLisa-Black.ttf
│  ├── MonoLisa-BlackItalic.ttf
│  ├── MonoLisa-Bold.ttf
│  ├── MonoLisa-BoldItalic.ttf
│  ├── MonoLisa-ExtraBold.ttf
│  ├── MonoLisa-ExtraBoldItalic.ttf
│  ├── MonoLisa-ExtraLight.ttf
│  ├── MonoLisa-ExtraLightItalic.ttf
│  ├── MonoLisa-Light.ttf
│  ├── MonoLisa-LightItalic.ttf
│  ├── MonoLisa-Medium.ttf
│  ├── MonoLisa-MediumItalic.ttf
│  ├── MonoLisa-Regular.ttf
│  ├── MonoLisa-RegularItalic.ttf
│  ├── MonoLisa-SemiBold.ttf
│  ├── MonoLisa-SemiBoldItalic.ttf
│  ├── MonoLisa-Thin.ttf
│  ├── MonoLisa-ThinItalic.ttf
│  ├── MonoLisaItalic.ttf
│  └── MonoLisaNormal.ttf
└── ttf - variable
   ├── README.md
   └── ttf
      ├── MonoLisaItalic.ttf
      └── MonoLisaNormal.ttf

monolisa-nerdfont-patch  main 🐧 
❯ make
==> MonoLisa NerdFont Patcher <==
:: Flags passed to font-patcher: -c
::: Patching MonoLisa/ttf... ⢿  
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-10-25 17:36 UTC-ML-D-GDK3.
 Based on source from git with hash: 8ce3216d492d4a249ffec163c005d098df28e58c
Nerd Fonts Patcher v2.3.0-RC (3.2.1) executing
Nerd Fonts: Font file does not exist: MonoLisa/ttf

:: ERROR: patching font file ttf see above for font-patcher output
make: *** [Makefile:8: patch] Error 1
```

A possible solution for consideration 

1. clone the folder structure provided by the user from ./MonoLisa to ./Patched. 2. find all `.ttf`, `.otf`, and `.woff2` files
3. patch all files in place

Example: After copying the file `MonoLisa/ttf - static/MonoLisa-Black.ttf` to `patched/ttf - static/MonoLisa-Black.ttf` patch it and overwrite the file `patched/ttf - static/MonoLisa-Black.ttf`. Or another approach is copying the folder structure to patch the file and store the new file in the same path under patched. 


This will make it so that the folder names and structure wouldn't matter. This will help in case Monolisa changes the file tree again in the future or if the users prefer to store their files in a specific structure.

**Comment by Bad3r** [comment]
Hmm it failed because the folder names do not match. Also in the latest release the variable fonts are nested inside another folder.
```py
monolisa-nerdfont-patch  main 🐧 
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

monolisa-nerdfont-patch  main 🐧 
❯ tree MonoLisa 
MonoLisa
├── faq.html
├── ttf - static
│  ├── MonoLisa-Black.ttf
│  ├── MonoLisa-BlackItalic.ttf
│  ├── MonoLisa-Bold.ttf
│  ├── MonoLisa-BoldItalic.ttf
│  ├── MonoLisa-ExtraBold.ttf
│  ├── MonoLisa-ExtraBoldItalic.ttf
│  ├── MonoLisa-ExtraLight.ttf
│  ├── MonoLisa-ExtraLightItalic.ttf
│  ├── MonoLisa-Light.ttf
│  ├── MonoLisa-LightItalic.ttf
│  ├── MonoLisa-Medium.ttf
│  ├── MonoLisa-MediumItalic.ttf
│  ├── MonoLisa-Regular.ttf
│  ├── MonoLisa-RegularItalic.ttf
│  ├── MonoLisa-SemiBold.ttf
│  ├── MonoLisa-SemiBoldItalic.ttf
│  ├── MonoLisa-Thin.ttf
│  ├── MonoLisa-ThinItalic.ttf
│  ├── MonoLisaItalic.ttf
│  └── MonoLisaNormal.ttf
└── ttf - variable
   ├── README.md
   └── ttf
      ├── MonoLisaItalic.ttf
      └── MonoLisaNormal.ttf

monolisa-nerdfont-patch  main 🐧 
❯ make
==> MonoLisa NerdFont Patcher <==
:: Flags passed to font-patcher: -c
::: Patching MonoLisa/ttf... ⢿  
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-10-25 17:36 UTC-ML-D-GDK3.
 Based on source from git with hash: 8ce3216d492d4a249ffec163c005d098df28e58c
Nerd Fonts Patcher v2.3.0-RC (3.2.1) executing
Nerd Fonts: Font file does not exist: MonoLisa/ttf

:: ERROR: patching font file ttf see above for font-patcher output
make: *** [Makefile:8: patch] Error 1
```

A possible solution for consideration 

1. clone the folder structure provided by the user from ./MonoLisa to ./Patched. 2. find all `.ttf`, `.otf`, and `.woff2` files
3. patch all files in place

Example: After copying the file `MonoLisa/ttf - static/MonoLisa-Black.ttf` to `patched/ttf - static/MonoLisa-Black.ttf` patch it and overwrite the file `patched/ttf - static/MonoLisa-Black.ttf`. Or another approach is copying the folder structure to patch the file and store the new file in the same path under patched. 


This will make it so that the folder names and structure wouldn't matter. This will help in case Monolisa changes the file tree again in the future or if the users prefer to store their files in a specific structure.

**Comment by daylinmorgan** [comment]
It should already be just be recreating the directory structure when patching. 

What's the output of `bin/get-font-files MonoLisa 'otf,ttf,woff,woff2'`

**Comment by Bad3r** [comment]
If you want to update the README, you can add 
> Tested with MonoLisa Complete 2.003

**Comment by Bad3r** [comment]
btw you might want to add `shfmt` as an optional dep

**Comment by daylinmorgan** [comment]
That's odd. It's not doing that on my machine.

What python version are you running? Could you try deleting the `patched` directory entirely and running again.

**Comment by Bad3r** [comment]
> That's odd. It's not doing that on my machine.
> 
> What python version are you running? Could you try deleting the `patched` directory entirely and running again.
```sh
❯ python --version                
Python 3.10.9
```
script output:
```sh
❯ make              
==> MonoLisa NerdFont Patcher <==
:: Flags passed to font-patcher: -c
:: ttf/MonoLisaItalic.ttf patched!
:: ttf/MonoLisaNormal.ttf patched!
:: ttf - static/MonoLisa-ExtraLight.ttf patched!
:: ttf - static/MonoLisa-Thin.ttf patched!
:: ttf - static/MonoLisa-SemiBold.ttf patched!
:: ttf - static/MonoLisa-Light.ttf patched!
:: ttf - static/MonoLisa-ExtraLightItalic.ttf patched!
:: ttf - static/MonoLisa-Medium.ttf patched!
:: ttf - static/MonoLisaItalic.ttf patched!
:: ttf - static/MonoLisa-RegularItalic.ttf patched!
:: ttf - static/MonoLisa-ThinItalic.ttf patched!
:: ttf - static/MonoLisa-BoldItalic.ttf patched!
:: ttf - static/MonoLisa-ExtraBold.ttf patched!
:: ttf - static/MonoLisa-MediumItalic.ttf patched!
:: ttf - static/MonoLisa-BlackItalic.ttf patched!
:: ttf - static/MonoLisa-LightItalic.ttf patched!
:: ttf - static/MonoLisaNormal.ttf patched!
:: ttf - static/MonoLisa-Regular.ttf patched!
:: ttf - static/MonoLisa-ExtraBoldItalic.ttf patched!
:: ttf - static/MonoLisa-Bold.ttf patched!
:: ttf - static/MonoLisa-SemiBoldItalic.ttf patched!
:: ttf - static/MonoLisa-Black.ttf patched!
:: fonts are patched
:: Happy typing!
make  162.93s user 2.08s system 99% cpu 2:45.33 total

❯ tree patched 
 patched
├──  ttf
│  ├──  MonoLisa Italic Nerd Font Complete.ttf
│  └──  MonoLisa Regular Nerd Font Complete.ttf
└──  ttf - static
   ├──  MonoLisa Black Italic Nerd Font Complete.ttf
   ├──  MonoLisa Black Nerd Font Complete.ttf
   ├──  MonoLisa Bold Italic Nerd Font Complete.ttf
   ├──  MonoLisa Bold Nerd Font Complete.ttf
   ├──  MonoLisa ExtraBold Italic Nerd Font Complete.ttf
   ├──  MonoLisa ExtraBold Nerd Font Complete.ttf
   ├──  MonoLisa ExtraLight Italic Nerd Font Complete.ttf
   ├──  MonoLisa ExtraLight Nerd Font Complete.ttf
   ├──  MonoLisa Italic Nerd Font Complete.ttf
   ├──  MonoLisa Light Italic Nerd Font Complete.ttf
   ├──  MonoLisa Light Nerd Font Complete.ttf
   ├──  MonoLisa Medium Italic Nerd Font Complete.ttf
   ├──  MonoLisa Medium Nerd Font Complete.ttf
   ├──  MonoLisa Regular Italic Nerd Font Complete.ttf
   ├──  MonoLisa Regular Nerd Font Complete.ttf
   ├──  MonoLisa SemiBold Italic Nerd Font Complete.ttf
   ├──  MonoLisa SemiBold Nerd Font Complete.ttf
   ├──  MonoLisa Thin Italic Nerd Font Complete.ttf
   └──  MonoLisa Thin Nerd Font Complete.ttf
```
Original file tree:
```sh
❯ exa --tree --icons --level=3 MonoLisa 
 MonoLisa
├──  faq.html
├──  ttf - static
│  ├──  MonoLisa-Black.ttf
│  ├──  MonoLisa-BlackItalic.ttf
│  ├──  MonoLisa-Bold.ttf
│  ├──  MonoLisa-BoldItalic.ttf
│  ├──  MonoLisa-ExtraBold.ttf
│  ├──  MonoLisa-ExtraBoldItalic.ttf
│  ├──  MonoLisa-ExtraLight.ttf
│  ├──  MonoLisa-ExtraLightItalic.ttf
│  ├──  MonoLisa-Light.ttf
│  ├──  MonoLisa-LightItalic.ttf
│  ├──  MonoLisa-Medium.ttf
│  ├──  MonoLisa-MediumItalic.ttf
│  ├──  MonoLisa-Regular.ttf
│  ├──  MonoLisa-RegularItalic.ttf
│  ├──  MonoLisa-SemiBold.ttf
│  ├──  MonoLisa-SemiBoldItalic.ttf
│  ├──  MonoLisa-Thin.ttf
│  ├──  MonoLisa-ThinItalic.ttf
│  ├──  MonoLisaItalic.ttf
│  └──  MonoLisaNormal.ttf
└──  ttf - variable
   ├──  README.md
   └──  ttf
      ├──  MonoLisaItalic.ttf
      └──  MonoLisaNormal.ttf
```
- Side note: If the folder `./patched` doesn't exist; the script crashes. It might be nice to create the folder if its missing `mkdir -p ./patched`

**Comment by daylinmorgan** [comment]
Path's are weird and I was being lazy with my operations. I changed things to use absolute and resolved paths which should recreate the weird directory structure these issues (and that `patched` is regenerated if necessary).

**Comment by Bad3r** [comment]
Awesome, thank you! Can confirm its working as expected now:
```sh
patched
├── ttf - static
│  ├── MonoLisa Black Italic Nerd Font Complete.ttf
│  ├── MonoLisa Black Nerd Font Complete.ttf
│  ├── MonoLisa Bold Italic Nerd Font Complete.ttf
│  ├── MonoLisa Bold Nerd Font Complete.ttf
│  ├── MonoLisa ExtraBold Italic Nerd Font Complete.ttf
│  ├── MonoLisa ExtraBold Nerd Font Complete.ttf
│  ├── MonoLisa ExtraLight Italic Nerd Font Complete.ttf
│  ├── MonoLisa ExtraLight Nerd Font Complete.ttf
│  ├── MonoLisa Italic Nerd Font Complete.ttf
│  ├── MonoLisa Light Italic Nerd Font Complete.ttf
│  ├── MonoLisa Light Nerd Font Complete.ttf
│  ├── MonoLisa Medium Italic Nerd Font Complete.ttf
│  ├── MonoLisa Medium Nerd Font Complete.ttf
│  ├── MonoLisa Regular Italic Nerd Font Complete.ttf
│  ├── MonoLisa Regular Nerd Font Complete.ttf
│  ├── MonoLisa SemiBold Italic Nerd Font Complete.ttf
│  ├── MonoLisa SemiBold Nerd Font Complete.ttf
│  ├── MonoLisa Thin Italic Nerd Font Complete.ttf
│  └── MonoLisa Thin Nerd Font Complete.ttf
└── ttf - variable
   └── ttf
      ├── MonoLisa Italic Nerd Font Complete.ttf
      └── MonoLisa Regular Nerd Font Complete.ttf
      ```
