### ISSUE TITLE
Not working properly?

### ISSUE THREAD

**Issue by flaticols** [daylinmorgan/monolisa-nerdfont-patch#2]
I got 
```shell
find: -printf: unknown primary or operator
make: Nothing to be done for `patch'.
```
after run `make`

 - macOS Ventura
 - MonoLisa 1.808
 - `fontforge` from brew
 - shell: fish

**Comment by daylinmorgan** [comment]
The version of `find` on  OSX doesn't support the `-printf` directive. I've swapped to just using `basename`. All I'm really using find for is to check which directories you have setup to decide which font extensions to patch.

**Comment by flaticols** [comment]
Thank, works now!
