### ISSUE TITLE
Dependency with `shfmt` is not documented

### ISSUE THREAD

**Issue by oxfist** [daylinmorgan/monolisa-nerdfont-patch#3]
I'm on a mac and got an error when running ``make lint` saying `shfmt` so I don't think it's installed by default. Installing it with `brew install shfmt" made it work.

Would you want a separate section for 'Requirements'? I can create a PR with the update.

```
**System Data**
System Version: macOS 12.6 (21G115)
Kernel Version: Darwin 21.6.0
```

**Comment by daylinmorgan** [comment]
You aren't the [first](https://github.com/daylinmorgan/monolisa-nerdfont-patch/issues/1#issuecomment-1358806279) to notice this. 

It's at best an optional or development dependency. All it's used for is applying formatting to the shell scripts found in `./bin`. Honestly, I don't use `shfmt` as much these days and instead rely on `shellcheck` integration with `neovim`. 

Now that I've expanded the `font-patcher` wrapper `./bin/patch-monolisa` to be a more involved python script, I will probably integrate `pre-commit` (for all linting/formatting) into the workflow. Though again this would only strictly be necessary for formatting/development. Not patching any fonts.

**Comment by daylinmorgan** [comment]
Switched to [`pre-commit` for linting](https://github.com/daylinmorgan/monolisa-nerdfont-patch/commit/916e85c67ca83570db976387b6774195a574f9a4).
