### ISSUE TITLE
Icons not filled in, with monolisa v2.011

### ISSUE THREAD

**Issue by hmajid2301** [daylinmorgan/monolisa-nerdfont-patch#5]
Hi,

I used this repo to patch my monolisa fonts without any issue. I decided to try to update monolisa to the latest version and patch it again, and now the nerd icons look a bit funny. They aren't filled in:

![image](https://github.com/daylinmorgan/monolisa-nerdfont-patch/assets/998807/38c2ccda-fde9-4256-bf6d-a9faf4e700dd)

Any ideas? Thanks!

**Comment by daylinmorgan** [comment]
Not sure when you last patched your font but this might be related to v3 of NerdFonts which moved some the of code points. You can find out more from the [release notes](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0). 

Is this a starship prompt? They also [patched](https://github.com/starship/starship/pull/5162) their community preset to use the correct symbols. 

If none of that helps you can try using [`nerdfix`](https://github.com/loichyan/nerdfix).

**Comment by hmajid2301** [comment]
I have a similar issue in neovim, so I suspect it is not just a starship issue :thinking:

**Comment by hmajid2301** [comment]
I think this ended up being unrelated, must've changed something else. I didn't have an emoji font to fallback to like Noto after doing that it fixed the issue. Nothing to do with your repo. Thanks!
